import Vue from 'vue'
import {
  Form,
  Pagination,
  Backtop,
  Loading,
  Switch,
  FormItem,
  TabPane,
  Card,
  Input,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Timeline,
  TimelineItem,
  Button,
  Menu,
  MenuItem,
  Submenu,
  Row,
  Col,
  Table,
  TableColumn,
  Select,
  Option,
  Dialog,
  Popover,
  Tabs
} from 'element-ui'
// const Vue = require('vue')
Vue.use(Dialog)
Vue.use(Option)
Vue.use(Select)
Vue.use(TableColumn)
Vue.use(Table)
Vue.use(Col)
Vue.use(Row)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Menu)
Vue.use(Button)
Vue.use(TimelineItem)
Vue.use(Timeline)
Vue.use(DropdownMenu)
Vue.use(Backtop)
Vue.use(DropdownItem)
Vue.use(Switch)
Vue.use(Pagination)
Vue.use(Loading)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Tabs)
Vue.use(Card)
Vue.use(TabPane)
Vue.use(Dropdown)
Vue.use(Popover)
